// timelineData.tsx
import { TimelineEntry } from "./types";

export const timelineData: TimelineEntry[] = [
    {
        title: "Project Lead",
        subtitle: "Meta Frazo · Full-time",
        dateRange: "Aug 2023 – Present · 1 yr 6 mos",
        location: "Champaign, Illinois, United States · Hybrid",
        description: "Leading the team at Meta Frazo. Building cutting-edge AI translation solutions.",
        link: "https://www.metafrazo.ai/",
        icon: "🚀",
        side: "left",
    },
    {
        title: "Software Engineer",
        subtitle: "State Farm · Internship",
        dateRange: "Aug 2024 – Present · 6 mos",
        location: "Champaign, Illinois, United States · Hybrid",
        description: "Property and Casualty Actuarial - Auto & Fire",
        icon: "🏢",
        side: "right",
    },
    {
        title: "Software Engineer",
        subtitle: "Snap Inc. · Internship",
        dateRange: "May 2024 – Aug 2024 · 4 mos",
        location: "Santa Monica, California, United States · On-site",
        description: "Monetization - Business Experience",
        icon: "👻",
        side: "left",
    },
    {
        title: "Software Engineer",
        subtitle: "State Farm · Internship",
        dateRange: "Jan 2024 – May 2024 · 5 mos",
        location: "Champaign, Illinois, United States · Hybrid",
        description: "Property and Casualty Actuarial - Competition",
        icon: "🏢",
        side: "right",
    },
    {
        title: "Software Engineer",
        subtitle: "State Farm · Internship",
        dateRange: "Aug 2023 – Dec 2023 · 5 mos",
        location: "Champaign, Illinois, United States · Hybrid",
        description: "Engineering",
        icon: "🏢",
        side: "left",
    },
    {
        title: "Software Engineer",
        subtitle: "State Farm · Internship",
        dateRange: "May 2023 – Aug 2023 · 4 mos",
        location: "Champaign, Illinois, United States · Hybrid",
        description: "Enterprise Data Enablement",
        icon: "🏢",
        side: "right",
    },

    {
        title: "Fitness Floor Associate",
        subtitle: "Sky Fitness Chicago · Part-time",
        dateRange: "Jun 2019 – Aug 2023 · 4 yrs 3 mos",
        location: "Buffalo Grove, Illinois, United States",
        description: "Maintained gym floor, assisted clients, and provided great customer service.",
        icon: "💪",
        side: "left",
    },
    {
        title: "Course Assistant @CS 124",
        subtitle: "University of Illinois Urbana-Champaign · Part-time",
        dateRange: "Jan 2022 – Aug 2023 · 1 yr 8 mos",
        location: "Champaign, Illinois, United States",
        description: "Helped teach and design assignments for CS 124.",
        link: "https://www.learncs.online/",
        icon: "🎓",
        side: "right",
    },
];
